# Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Environment Properties
minecraft_version=26.2
minecraft_version_range=[26.2]

neo_version=26.2.0.6-beta

## Mod Properties
mod_id=cosmicore
mod_name=Cosmicore
mod_license=MIT
mod_version=1.0.0
mod_group_id=net.nova.cosmicore
mod_authors=ImVeryBad, Foxirion
mod_description=Explore the world for the strange space stones, but beware the skies because- METEORS INCOMING!